server:
  port: 8088

spring:
  application:
  name: my-restful-service
  message:
    basename: messages
#  security:
#    user:
#      name: username
#      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"